Added section how to sign and verify container image.
Azure-Samples/aks-labs pull request #25
Opened 2024-11-06 21:24 UTC by russd2357

Added a Secure Supply Chain exercise to build, sign and verify container images using Notation CLI

2024-11-06 23:26 UTC, pauldotyu requested changes
Haven't gone through the step-by-step process yet, but content looks great! Only major question is around keyvault and container registry resource creation.

2024-11-06 23:26 UTC, pauldotyu commented on workshops/advanced-aks/workshop.md
> +AKV_NAME="myKeyVault${RANDOM}"
I thought the keyvault and container registry will be a part of the bicep deployment, if so, then we don't need these variables.

2024-11-06 23:26 UTC, pauldotyu commented on workshops/advanced-aks/workshop.md
> +```
Same as my comment above, thought these resources were going to be pre-provisioned in the bicep.

2024-11-06 23:26 UTC, pauldotyu commented on workshops/advanced-aks/workshop.md
> +```
I'd remove the numbering to keep consistent with the rest of the lab content

2024-11-06 23:26 UTC, pauldotyu commented on workshops/advanced-aks/workshop.md
>  - Image Cleaner
If we aren't visiting image cleaner, then we should remove this.

2024-11-06 23:26 UTC, pauldotyu commented on workshops/advanced-aks/workshop.md
> +<div class="info" data-title="Important">
I think we want to keep the css class as `important`

```suggestion
<div class="important" data-title="Important">
```

2024-11-06 23:26 UTC, pauldotyu commented on workshops/advanced-aks/workshop.md
> +<div class="info" data-title="Important">
I think we want to keep the css class as `important`

```suggestion
<div class="important" data-title="Important">
```

2024-11-07 18:38 UTC, russd2357 commented on workshops/advanced-aks/workshop.md
> +AKV_NAME="myKeyVault${RANDOM}"
We set the variables because they are referenced in the lab exercises. What we need to do is update the Bicep spec to include outputs for the resource names and ids created. Then we can use them to initialize the environment variables.

2024-11-07 18:44 UTC, russd2357 commented on workshops/advanced-aks/workshop.md
>  - Image Cleaner
Yep.

2024-11-07 18:45 UTC, russd2357 commented on workshops/advanced-aks/workshop.md
> +<div class="info" data-title="Important">
NP. I thought I accidentally munged it.

2024-11-07 19:31 UTC, russd2357 commented on workshops/advanced-aks/workshop.md
> +```
Ok

2024-11-07 20:55 UTC, merged